- cmd/server/app.go
- internal/handler/employee/employee.go
- internal/helper/employees_mapper.go
- internal/repository/employee/employee.go
- internal/repository/employee/i_employee.go
- internal/service/employee/employee.go
- internal/service/employee/i_employee.go
**Overview**
This PR adds a new _GET_ endpoint `/api/v1/employees/{id}` to retrieve a specific employee by their ID.
- Implemented the new endpoint.
- Added error handling for invalid IDs.
- Access `/api/v1/employees/{id}` to verify the JSON response for a specific employee.
> Feature get employee

- cmd/server/app.go
- internal/handler/product/product.go
- internal/repository/product/i_product.go
- internal/repository/product/product.go
- internal/service/product/i_product.go
- internal/service/product/product.go
Overview
This PR adds a new POST endpoint /api/v1/product to create a new product in the system
Changes Made
Added validation and error handling.
How to Test
Access /api/v1/product to create a new buyer and verify the JSON response.
> Feature create product

- cmd/server/app.go
- internal/domain/dto/product_dto.go
- internal/handler/product/product.go
- internal/helper/product_mapper.go
- internal/loader/loader.go
- internal/repository/product/i_product.go
- internal/repository/product/product.go
- internal/service/product/i_product.go
- internal/service/product/product.go
Overview
This PR adds a new DELETE endpoint /api/v1/product/{id} to create a new product in the system
Changes Made
Added validation and error handling.
How to Test
Access /api/v1/product/{id} to delete a product and verify the JSON response.
> Feature delete product

- cmd/server/app.go
- internal/domain/dto/warehouse_dto.go
- internal/domain/model/warehouse.go
- internal/handler/warehouse/warehouse.go
- internal/helper/warehouse_mapper.go
- internal/loader/loader.go
- internal/repository/warehouse/i_warehouse.go
- internal/repository/warehouse/warehouse.go
- internal/service/warehouse/i_warehouse.go
- internal/service/warehouse/warehouse.go
**Overview**
This PR adds a new GET endpoint /api/v1/warehouses/{id} to get a warehouse by id
Access /api/v1/warehouses/{id} to get a product by id.
> Feature get warehouse by id

- cmd/server/app.go
- internal/handler/employee/employee.go
- internal/repository/employee/employee.go
- internal/repository/employee/i_employee.go
- internal/service/employee/employee.go
- internal/service/employee/i_employee.go
**Overview**
This PR adds the endpoint _PATCH_ `/api/employees/{id}` to update an employee's details in the system using the PATCH method.
- Implemented the endpoint for updating an employee.
- Added input validation to ensure only valid fields are updated.
- Included error handling for non-existent employees.
- Send a _PATCH_ request to the endpoint _PATCH_ `/api/employees/{id}` with valid data to update the employee's details.
- Verify the response and check if the employee's information was correctly updated.
- Attempt to update a non-existent employee to ensure proper error handling.
> Feature update employee

- cmd/server/app.go
- internal/domain/dto/buyer_dto.go
- internal/domain/model/buyer.go
- internal/handler/buyer/buyer.go
- internal/helper/buyer_mapper.go
- internal/loader/loader.go
- internal/repository/buyer/buyer.go
- internal/repository/buyer/i_buyer.go
- internal/service/buyer/buyer.go
- internal/service/buyer/i_buyer.go
- pkg/error_handler/my_error.go
**Overview**
This PR adds a new GET endpoint /api/v1/buyers/{id} to get a buyer by his ID
- Fixed previous code to be in line with standard set by the team
- Implemented the new endpoint.
- Removed ping endpoint present since the beginning for testing purposes
- Access /api/v1/buyers/{id} to list a specific buyer by his ID and verify the JSON response
> Feature get buyer by id

- internal/handler/product/product.go
- internal/repository/product/product.go
Overview
This PR refactors the UPDATE method in the repository to better improve code readability and flow. It also fixes the mistakenly place Status Code 200 on the Delete method for the proper Status No Content 204
Changes Made
Refactor the UpdateProduct method on the repository package
Fix the Status Code present in the DELETE handler method
How to Test
Access /api/v1/product/{id} to patch a product and verify the JSON response.
> Refactor product update

- cmd/server/app.go
- internal/handler/section/section.go
- internal/repository/section/i_section.go
- internal/repository/section/section.go
- internal/service/section/i_section.go
- internal/service/section/section.go
- tmp/build-errors.log
✅ Implemented the full Delete flow
Send a DELETE request to the endpoint DELETE /api/sections/{id} with a valid section ID and verify the response.
> Feature Section-Delete#5

- cmd/server/app.go
- internal/domain/model/warehouse.go
- internal/handler/warehouse/warehouse.go
- internal/repository/warehouse/i_warehouse.go
- internal/repository/warehouse/warehouse.go
- internal/service/warehouse/i_warehouse.go
- internal/service/warehouse/warehouse.go
**Overview**
This PR adds a new PATCH endpoint /api/v1/warehouses/{id} to update a warehouse
Access /api/v1/warehouses/{id} and send a body to update a warehouse.
> ✨ feat: Update warehouse by id

- cmd/server/app.go
- internal/handler/warehouse/warehouse.go
- internal/repository/warehouse/i_warehouse.go
- internal/repository/warehouse/warehouse.go
- internal/service/warehouse/i_warehouse.go
- internal/service/warehouse/warehouse.go
**Overview**
This PR adds a new DELETE endpoint /api/v1/warehouses/{id} to delete a warehouse
Access /api/v1/warehouses/{id} to delete a warehouse.
> ✨ feat: delete warehouse by id

- cmd/server/app.go
- internal/handler/section/section.go
- internal/repository/section/i_section.go
- internal/repository/section/section.go
- internal/service/section/i_section.go
- internal/service/section/section.go
This Pr implemets the Patch flow
Changes made
✅ Implemented the full Patch flow
How to Test
Send a PATCH request to the endpoint PATCH /api/sections/{id} with a valid section ID and verify the response.
> Feature Section-Update#4

- cmd/server/app.go
- internal/handler/buyer/buyer.go
- internal/repository/buyer/buyer.go
- internal/repository/buyer/i_buyer.go
- internal/service/buyer/buyer.go
- internal/service/buyer/i_buyer.go
- pkg/error_handler/my_error.go
**Overview**
This PR adds a new PATCH endpoint /api/v1/buyers/{id} to update buyer fields
- Implemented the new endpoint
- Updated handler, service and repository layers from buyer to be able to do the update
- Verified error handling is done for simple edge cases
- Access /api/v1/buyers/{id} to Patch a specific buyer by his ID and verify the JSON response
_Feedback is appreciated!_
> Feature Update Buyer

- Daily.md
- internal/domain/dto/employee_dto.go
- internal/domain/model/employee.go
- internal/handler/employee/employee.go
- internal/helper/employees_mapper.go
- internal/repository/employee/employee.go
- internal/repository/employee/i_employee.go
- internal/service/employee/employee.go
- internal/service/employee/i_employee.go
**Overview**
This PR refactors the _PATCH_ implementation for updating employee details to include proper field validation using pointers.
- Refactored the _PATCH_ endpoint logic to validate request fields dynamically.
- Implemented pointer receivers for the employee struct to facilitate optional field updates.
- Send _PATCH_ requests to `PATCH /api/employees/{id}` with various payloads, including both complete and partial updates.
- Verify that the correct fields are updated based on provided data, and that invalid fields return appropriate error messages.
> Fixture patch validation

- cmd/server/app.go
- internal/domain/dto/seller_dto.go
- internal/domain/model/seller.go
- internal/handler/seller/seller.go
- internal/helper/seller_mapper.go
- internal/repository/seller/i_seller.go
- internal/repository/seller/seller.go
- internal/service/seller/i_seller.go
- internal/service/seller/seller.go
Overview
This PR adds a new PATCH endpoint /api/v1/sellers/{id} to update a seller
Changes Made
Implemented the new endpoint
Updated handler, service and repository layers from sellers to be able to do the update
How to Test
Access /api/v1/sellers/{id} to Patch a specific seller by his ID and verify the JSON response
> Feature update seller

- Daily.md
- internal/domain/dto/buyer_dto.go
- internal/domain/model/buyer.go
- internal/handler/buyer/buyer.go
- internal/helper/buyer_mapper.go
- internal/repository/buyer/buyer.go
- internal/repository/buyer/i_buyer.go
- internal/service/buyer/buyer.go
- internal/service/buyer/i_buyer.go
**Overview**
This PR refactors the PATCH implementation for updating buyer details to include proper field validation using pointers.
- Refactored the PATCH endpoint logic to differentiate between "zero value" and "not present" fields.
- Implemented pointer receivers for the buyer struct to facilitate optional field updates.
- Send PATCH requests to PATCH /api/buyers/{id} with various payloads, including complete, partial and blank updates.
- Verify that the correct fields are updated based on provided data, and that invalid fields return appropriate error messages.
> Refactor patch product

- internal/handler/warehouse/warehouse.go
- internal/repository/warehouse/warehouse.go
- pkg/error_handler/my_error.go
**Overview**
This PR refactors the error implementation and add that implementation to the warehouses endpoint.
Refactored the error handling and implemented it in warehouses.
Test for the different types of errors in the different warehouses endpoints.
> Feature handle errors

- internal/handler/product/product.go
- internal/helper/product_mapper.go
- internal/repository/product/product.go
- internal/service/product/product.go
- pkg/error_handler/my_error.go
Overview / Changes Made
Refactored the error handling in the application for easier testing and readability.
Feedback is appreciated!!
> Refactor product error

- internal/domain/dto/buyer_dto.go
- internal/handler/buyer/buyer.go
- internal/repository/buyer/buyer.go
**Overview**
This PR refactors the error handling related to buyer entity. Now it's updated according to the standard set by the team that include:
- Using the helper package, it's variables and functions
- Only handle error logic and validations in handler layer using HandleError function
- Using the bootcamp-go/web package for responses
- Refactored the repository and handler layers to use the functions and variables defined in helper package.
- Added a status message for successful responses
- Send request to every endpoint from /api/buyers/ with various payloads that test edge cases that cause errors 
- Verify the HTTP status and messages from responses
_Feedback is welcome!_
> Refactor Buyer Error Handling 

- internal/handler/employee/employee.go
- internal/repository/employee/employee.go
- internal/service/employee/employee.go
**Overview**
This PR refactors the codebase to centralize and abstract error handling, improving maintainability and readability.
- Removed repetitive error handling code from various endpoints and replaced it with a unified approach.
- Improved error messages for better clarity and consistency across the application.
- Test various endpoints to ensure that errors are handled uniformly and return consistent responses.
- Verify that error messages are clear and informative, reflecting the underlying issues appropriately.
- Check that no functionality has been broken after the refactor.
> Refactor employee errors

- internal/handler/seller/seller.go
- internal/repository/seller/seller.go
- internal/service/seller/seller.go
Overview
With this PR, error handling is refactored in the repository, service, and handler layers for the Seller entity. All error handling is centralized and generalized, for which general functions are implemented in the helper package.
How to Test
Send request to every endpoint from /api/Sellers/ with various payloads that test edge cases that cause errors
Verify the HTTP status and messages from responses
> Refactor Seller Error Handling

- internal/domain/dto/section_dto.go
- internal/domain/model/section.go
- internal/handler/section/section.go
- internal/helper/section_mapper.go
- internal/repository/section/i_section.go
- internal/repository/section/section.go
- internal/service/section/i_section.go
- internal/service/section/section.go
- pkg/error_handler/my_error.go
- tmp/build-errors.log
✅ Changes in push handling, pointers are used to allow 0 values
✅ error handling is standardized
> Refactor-section

- Daily.md
Overview
Update the file daily.md with the description of my activities in the first sprint
> Update file daily

- cmd/server/app.go
- internal/domain/dto/inbound_order_dto.go
- internal/domain/model/inbound_order.go
- internal/handler/inbound_order/inbound_order.go
- internal/helper/inbound_order_mapper.go
- internal/repository/employee/employee.go
- internal/repository/inbound_order/i_inbound_order.go
- internal/repository/inbound_order/inbound_order.go
- internal/service/inbound_order/i_inbound_order.go
- internal/service/inbound_order/inbound_order.go
- pkg/error_handler/my_error.go
**Overview**
This PR implements the functionality to create a new inbound order in the system `POST /api/v1/inboundOrders`.
- Added an endpoint for creating a new inbound order.
- Implemented input validation and error handling.
- Access the endpoint `POST /api/v1/inboundOrders` and verify the response with valid and invalid data.
> Feature create inboundorder

- .gitignore
- cmd/server/app.go
- internal/domain/dto/buyer_dto.go
- internal/domain/model/buyer.go
- internal/handler/buyer/buyer.go
- internal/helper/buyer_mapper.go
- internal/loader/loader.go
- internal/repository/buyer/buyer.go
- internal/repository/buyer/i_buyer.go
- internal/service/buyer/buyer.go
- internal/service/buyer/i_buyer.go
- pkg/error_handler/my_error.go
**Overview**
This PR refactors the code to implement database functionality for buyers and includes slight modifications of gitignore file and correcting issues related to the database connection implementation.
- Refactored the codebase to integrate database functionality.
- Modified the .gitignore file to exclude propietary files from IDEs
- Corrected various issues related to the setup of the database connection. 
- Ensured proper configuration for connecting to the database.
- Verify that the database connection and related endpoints are functioning as expected.
- Validate that any relevant changes in the database functionality work as intended.
> Refactor buyer sql implementation

- cmd/server/app.go
- internal/domain/dto/purchase_order_dto.go
- internal/domain/model/order_status.go
- internal/domain/model/purchase_order.go
- internal/handler/purchase_order/purchase_order.go
- internal/helper/purchase_order_mapper.go
- internal/repository/buyer/buyer.go
- internal/repository/purchase_order/i_purchase_order.go
- internal/repository/purchase_order/purchase_order.go
- internal/service/purchase_order/i_purchase_order.go
- internal/service/purchase_order/purchase_order.go
- pkg/error_handler/my_error.go
**Overview**
This pull request introduces the functionality to create purchase orders within the application in the route POST /api/v1/purchaseOrders.
- Add purchase order repository, service, and handler: Implemented the necessary components to handle purchase orders, including the repository, service layer, and request handlers.
- Access the endpoint POST /api/v1/purchaseOrders, verify the response with valid data an test edge cases with invalid data
> Feature Create Purchase Order

- cmd/server/app.go
- internal/domain/dto/seller_dto.go
- internal/domain/model/seller.go
- internal/helper/seller_mapper.go
- internal/repository/seller/i_seller.go
- internal/repository/seller/seller.go
- internal/service/seller/i_seller.go
- internal/service/seller/seller.go
- pkg/error_handler/my_error.go
Overview
This PR refactors the code to implement database functionality for sellers
Changes Made
Refactored the codebase to integrate database functionality.
were refactored Models and DTOs  for sellers
How to Test
Verify that the database connection is functioning as expected.
Ensure that the .gitignore file is correctly ignoring the specified files and directories.
Validate that any relevant changes in the database functionality work as intended.
> Refactor seller sql implementation

- cmd/server/app.go
- internal/domain/dto/employee_dto.go
- internal/domain/model/employee.go
- internal/handler/employee/employee.go
- internal/helper/employees_mapper.go
- internal/repository/employee/employee.go
- internal/repository/employee/i_employee.go
- internal/service/employee/employee.go
- internal/service/employee/i_employee.go
**Overview**
This PR introduces the implementation of the `GET /api/v1/employees/reportInboundOrders?id={employeeId}` endpoint, which retrieves inbound order statistics for employees.
- Implemented a new API endpoint to generate reports on inbound orders for employees.
- Updated the backend logic to handle requests and generate accurate reports based on the provided id parameter.
- Refactored relevant models and data transfer objects (DTOs) related to employees and inbound orders.
- Send a GET request to `/api/v1/employees/reportInboundOrders?id=1` and verify that the response returns the correct number of inbound orders for the specified employee.
- Test the endpoint without the `id` parameter to ensure it returns the total inbound …
> Feature report inboundorders

- cmd/server/dependency_injection.go
- internal/handler/product/product.go
- internal/handler/product_record/product_record.go
- internal/repository/product/product.go
- internal/repository/product_record/i_product_record.go
- internal/repository/product_record/product_record.go
- internal/service/product/product.go
- internal/service/product_record/i_product_record.go
- internal/service/product_record/product_record.go
Overview
This PR refactors the product record CREATE method for it to not access the product repository remotely, but instead takes advantage of the GetByID method present on the product service.
It also refactors some of the comments present through out the application on the product and product_record files (repository, service and handler)
> Refactor product record

- cmd/server/dependency_injection.go
- internal/repository/buyer/buyer.go
- internal/repository/carry/carry.go
- internal/repository/carry/i_carry.go
- internal/repository/inbound_order/inbound_order.go
- internal/repository/order_status/i_order_status.go
- internal/repository/order_status/order_status.go
- internal/service/purchase_order/purchase_order.go
- pkg/error_handler/my_error.go
**Overview**
This PR refactors the code to implement the standards set by the team to manage database (specifically foreing keys) errors.
- Refactored buyer repository to override database errors
- Created order status repo to validate existence of this entity
- Refactored Purchase Order service to manage validations for all related foreing keys
- Modified the dependency injection file to include the external repositories needed to validate foreing keys on Purchase Orders
- Verify that POST requests made to /api/v1/purchaseOrders are validating foreing keys by sending non existent IDs in those fields
- Verify that requests with correct data still works as intended
> Refactor buyer error handling

- cmd/server/app.go
- cmd/server/dependency_injection.go
- internal/domain/dto/locality_dto.go
- internal/domain/dto/seller_dto.go
- internal/domain/model/locality.go
- internal/domain/model/seller.go
- internal/handler/locality/locality.go
- internal/helper/locality_mapper.go
- internal/helper/seller_mapper.go
- internal/repository/carry/carry.go
- internal/repository/country/country.go
- internal/repository/locality/i_locality.go
- internal/repository/locality/locality.go
- internal/repository/province/province.go
- internal/repository/seller/seller.go
- internal/service/locality/i_locality.go
- internal/service/locality/locality.go
- internal/service/seller/seller.go
- pkg/error_handler/my_error.go
Overview
This PR introduces the implementation of the GET /api/v1/localities/reportSellers?id={localityId} endpoint, which retrieves sellers for locality.
Changes Made
Enhanced error handling to provide more informative responses when foreign key validations fail.
How to Test
Send a GET request to /api/v1/localities/reportSellers?id=1 and verify that the response returns the correct number of sellers for locality.
Test the endpoint without the id parameter to ensure it returns the total of localities with its sellers.
> Feature report sellers

- internal/domain/dto/product_dto.go
- internal/domain/dto/product_record_dto.go
- internal/domain/model/product.go
- internal/domain/model/product_record.go
- internal/handler/product/product.go
- internal/helper/product_mapper.go
- internal/helper/product_record_mapper.go
- internal/repository/product/i_product.go
- internal/repository/product/product.go
- internal/service/product/i_product.go
- internal/service/product/product.go
- internal/service/product_record/product_record.go
Overview
This PR refactors the product and product records MODELS and DTOs to implement embedding to avoid the creation of unnecessary structures for the same purpose.
It also refactors the methods and interfaces that revolve around those structures.
> Refactor Product and Product Records MODELS and DTOs with their methods accordingly 

- internal/domain/dto/employee_dto.go
- internal/domain/model/employee.go
- internal/handler/employee/employee.go
- internal/helper/employees_mapper.go
- internal/repository/employee/employee.go
- internal/repository/employee/i_employee.go
- internal/service/employee/employee.go
- internal/service/employee/i_employee.go
**Overview**
This PR refactors the employee Data Transfer Object (DTO) structure to simplify its design and updates the related methods to ensure that the employee endpoint functions perfectly.
- Simplified Employee DTO Structure: Refactored the employee DTO to make it more streamlined and easier to work with. This simplification improves clarity and maintainability of the code.
- Updated Related Methods: Modified the methods associated with the employee endpoint to align with the new DTO structure. This includes adjustments in the data handling and response formatting to ensure consistency and correctness.
- Verify the` /api/v1/employees` endpoint to ensure that all operations (_GET, POST, PATCH, DELETE_) function correctly with the …
> Fixture employee pointers

- internal/domain/dto/locality_dto.go
- internal/domain/dto/seller_dto.go
- internal/domain/model/locality.go
- internal/domain/model/seller.go
- internal/handler/seller/seller.go
- internal/helper/locality_mapper.go
- internal/helper/seller_mapper.go
- internal/repository/locality/i_locality.go
- internal/repository/locality/locality.go
- internal/repository/seller/i_seller.go
- internal/repository/seller/seller.go
- internal/service/locality/i_locality.go
- internal/service/locality/locality.go
- internal/service/seller/i_seller.go
- internal/service/seller/seller.go
Overview
In this PR the suggested changes for sprint 1 are implemented
Changes Made
Embedded DTOs that had redundant code
Fixed mappers to work with new DTOs
Using slices instead of maps to store response data
Fixed imports and method names for sellers and localities repositories
How to Test
Verify that /api/v1/sellers and api/v1/localities create method is returning the right fields on deserialization (DTO)
Check if normal functionalities are still working as intended
> Refactor requirement 1

- internal/domain/dto/section_dto.go
- internal/domain/model/section.go
- internal/handler/section/section.go
- internal/helper/section_mapper.go
- internal/repository/section/i_section.go
- internal/repository/section/section.go
- internal/service/section/i_section.go
- internal/service/section/section.go
Overview
This PR refactors the Sections and Products Batch MODELS and DTOs to implement embedding to avoid the creation of unnecessary structures for the same purpose.
It also refactors the methods and interfaces that revolve around those structures.
> Refactor Sections and Product Batch MODELS and DTOs
